/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.employee;

import com.dbconnection.DBconnect;
import com.login.login;
import com.main.main;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author cheythi
 */
public class add_employee extends javax.swing.JFrame {

    //DBconnection
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    
    public add_employee() {
        initComponents();
        header.setBackground(new Color(0,0,0,180));
        logout.setBackground(new Color(255,51,0,180));
        menu.setBackground(new Color(255,51,0,180));
        att_pnl.setBackground(new Color(255,51,0,180));
        report_pnl.setBackground(new Color(255,51,0,180));
        ed.setBackground(new Color(51,51,51,180));
        etable.setBackground(new Color(51,51,51,180));
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        
        //connect to db
        
        con = DBconnect.connect();
        
        //loadtable
        tableload();
       
    }
    
    /**
     *
     */
    public void tableload(){
    
        try{
        String sql ="SELECT  EID, NIC, GENDER, FIRSTNAME, LASTNAME, ADDRESS, TELEPHONE, BASIC_SAL FROM  employee";
        pst = (PreparedStatement) con.prepareStatement(sql);
        rs = (ResultSet) pst.executeQuery();
        
        
        etable.setModel(DbUtils.resultSetToTableModel((ResultSet) rs));
      
        }
        catch(SQLException e){
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        att_pnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        report_pnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ed = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        basicsal = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        show_emp_id = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        etable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        sseid = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(null);

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Log out");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(0, 359, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 359, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        background.add(logout);
        logout.setBounds(0, 800, 780, 50);

        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        background.add(header);
        header.setBounds(0, 0, 1550, 70);

        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Menu");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background.add(menu);
        menu.setBounds(780, 800, 770, 50);

        att_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                att_pnlMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Attendance");

        javax.swing.GroupLayout att_pnlLayout = new javax.swing.GroupLayout(att_pnl);
        att_pnl.setLayout(att_pnlLayout);
        att_pnlLayout.setHorizontalGroup(
            att_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(att_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, att_pnlLayout.createSequentialGroup()
                    .addContainerGap(301, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addContainerGap(302, Short.MAX_VALUE)))
        );
        att_pnlLayout.setVerticalGroup(
            att_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(att_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, att_pnlLayout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        background.add(att_pnl);
        att_pnl.setBounds(0, 70, 780, 50);

        report_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                report_pnlMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Report");

        javax.swing.GroupLayout report_pnlLayout = new javax.swing.GroupLayout(report_pnl);
        report_pnl.setLayout(report_pnlLayout);
        report_pnlLayout.setHorizontalGroup(
            report_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(report_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_pnlLayout.createSequentialGroup()
                    .addContainerGap(330, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(320, Short.MAX_VALUE)))
        );
        report_pnlLayout.setVerticalGroup(
            report_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
            .addGroup(report_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_pnlLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        background.add(report_pnl);
        report_pnl.setBounds(780, 70, 770, 50);

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel5.setText("Employee Details");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("NIC");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("First Name");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Last  Name");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Address");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Telephone NO");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Basic Salary");

        nic.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicKeyPressed(evt);
            }
        });

        fname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
        });

        lname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameKeyPressed(evt);
            }
        });

        address.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        telephone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        telephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telephoneKeyPressed(evt);
            }
        });

        basicsal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        basicsal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        basicsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                basicsalKeyPressed(evt);
            }
        });

        gender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Gender--", "Male", "Female" }));
        gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add.setText("ADD");
        add.setBorder(null);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.setBorder(null);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteMousePressed(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        show_emp_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        show_emp_id.setText("Employee ID");

        empid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        empid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout edLayout = new javax.swing.GroupLayout(ed);
        ed.setLayout(edLayout);
        edLayout.setHorizontalGroup(
            edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edLayout.createSequentialGroup()
                        .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(show_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edLayout.createSequentialGroup()
                        .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telephone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nic)
                    .addComponent(fname)
                    .addComponent(lname)
                    .addComponent(basicsal)
                    .addComponent(gender, 0, 260, Short.MAX_VALUE)
                    .addComponent(empid))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(edLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        edLayout.setVerticalGroup(
            edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(show_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicsal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(edLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        background.add(ed);
        ed.setBounds(30, 130, 590, 660);

        etable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        etable.setForeground(new java.awt.Color(204, 204, 204));
        etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EID", "NIC", "First Name", "Last Name", "Gender", "Address", "Telephone NO", "Basic Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        etable.setAlignmentX(2.0F);
        etable.setAlignmentY(2.0F);
        etable.setEditingColumn(2);
        etable.setEditingRow(2);
        etable.setRowHeight(30);
        etable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(etable);
        if (etable.getColumnModel().getColumnCount() > 0) {
            etable.getColumnModel().getColumn(0).setPreferredWidth(50);
            etable.getColumnModel().getColumn(1).setPreferredWidth(120);
            etable.getColumnModel().getColumn(2).setPreferredWidth(150);
            etable.getColumnModel().getColumn(3).setResizable(false);
            etable.getColumnModel().getColumn(3).setPreferredWidth(200);
            etable.getColumnModel().getColumn(4).setResizable(false);
            etable.getColumnModel().getColumn(4).setPreferredWidth(80);
            etable.getColumnModel().getColumn(5).setPreferredWidth(200);
            etable.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        background.add(jScrollPane1);
        jScrollPane1.setBounds(650, 220, 880, 520);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setText("Employee ID");
        background.add(jLabel14);
        jLabel14.setBounds(920, 110, 170, 50);

        sseid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sseid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.add(sseid);
        sseid.setBounds(860, 160, 270, 40);

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("SEARCH");
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        background.add(search);
        search.setBounds(1160, 160, 110, 40);
        background.add(image);
        image.setBounds(10, 0, 1550, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void att_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_att_pnlMouseClicked
        attendance at1 = new attendance();
        at1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_att_pnlMouseClicked

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    //----------------------------------------------insert---------------------------------------------------------------------
    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        // TODO add your handling code here:
        
   
    }//GEN-LAST:event_addMousePressed

    //-----------------------------------------------table-------------------------------------------------------------
    private void etableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etableMousePressed
        // TODO add your handling code here:
   
    
    
    
    }//GEN-LAST:event_etableMousePressed

    //---------------------------------------------------------------------update-----------------------------------------------------------------------------------------------------
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
       int x= JOptionPane.showConfirmDialog(null, "Do you really wnat to update?");
       if(x==0){
           
       
        String eid = empid.getText();
        String efname = fname.getText();
        String elname = lname.getText();
        String eaddress = address.getText();
        String etelephone = telephone.getText();
        String ebasicsal= basicsal.getText();
        
        try{
        
   
       String sql = "UPDATE employee SET   FIRSTNAME='"+efname+"',LASTNAME='"+elname+"' ,ADDRESS='"+eaddress+"',TELEPHONE='"+etelephone+"', BASIC_SAL='"+ebasicsal+"' WHERE EID='"+eid+"' ";
       pst = (PreparedStatement) con.prepareStatement(sql);
       
       pst.execute();
       
       tableload();
           
       
       }   catch (SQLException ex) {
               Logger.getLogger(add_employee.class.getName()).log(Level.SEVERE, null, ex);
           }
        
        empid.setText("");
        nic.setText("");
        gender.setSelectedItem("--Select Gender--");
        fname.setText("");
        lname.setText("");
        address.setText("");
        telephone.setText("");
        basicsal.setText("");
        
     
    }//GEN-LAST:event_updateActionPerformed
    }
    private void deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMousePressed
        // TODO add your handling code here:
        
        //--------------------------delete---------------------------------
     
      
        
    
    }//GEN-LAST:event_deleteMousePressed

    //---------------------------------search--------------------------------------------
    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchMousePressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        String seid = sseid.getText();
        
         if(sseid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter Employee ID");
        }
        
       String sql ="SELECT EID, NIC, GENDER, FIRSTNAME, LASTNAME, ADDRESS, TELEPHONE, BASIC_SAL from employee where EID='"+ seid +"' ";
       
        try {
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs=(ResultSet) pst.executeQuery();
            etable.setModel(DbUtils.resultSetToTableModel((ResultSet) rs));
        } catch (SQLException ex) {
            Logger.getLogger(add_employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           sseid.setText("");
    }//GEN-LAST:event_searchActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

                
       
              
              
 if( nic.getText().equals(" ") || gender.getSelectedItem().equals(" ") || fname.getText().equals(" ") || lname.getText().equals(" ") ||  address.getText().equals( "")|| telephone.getText().equals( "")|| basicsal.getText().equals(""))
 {
     JOptionPane.showMessageDialog(rootPane, "Required fields cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
 }
 
            
    //validation    
                

 else{        
        String eid = empid.getText();
        String enic=nic.getText();
        String egender= gender.getSelectedItem().toString();
        String efname = fname.getText();
        String elname = lname.getText();
        String eaddress = address.getText();
        String etelephone = telephone.getText();
        String ebasicsal= basicsal.getText();
        
        
       // PreparedStatement pst;
        
        try{
                String q = "INSERT INTO employee (NIC, GENDER, FIRSTNAME, LASTNAME, ADDRESS, TELEPHONE, BASIC_SAL) values (?,?,?,?,?,?,?) ";
        
        pst = (PreparedStatement) con.prepareStatement(q);
        pst.setString(1, enic);
        pst.setString(2, egender);
        pst.setString(3, efname);
        pst.setString(4, elname);
        pst.setString(5, eaddress);
        pst.setString(6, etelephone);
        pst.setString(7, ebasicsal); 
            
        
        
        pst.executeUpdate();
        
        tableload();
        }
        catch(SQLException e){
        }
        
        empid.setText("");
        nic.setText("");
        gender.setSelectedItem("--Select Gender--");
        fname.setText("");
        lname.setText("");
        address.setText("");
        telephone.setText("");
        basicsal.setText("");
        
              }
    
        
        
        
        
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
       // --------------------------delete---------------------------------
        
        int x = JOptionPane.showConfirmDialog(null,"Do you really want to delete this?");
        
        if(x==0)
        {
                     String eid = empid.getText();
                     
                     //String sql ="DELETE from employee where EID='"+ eid+"'";
                     
                     String sql = "DELETE FROM employee WHERE EID='"+ eid+"' ";
                     
                     try{
                        pst = (PreparedStatement) con.prepareStatement(sql);
                        
                        pst.execute();
                        
                        tableload();
                        
                        
                     } catch (SQLException ex) {
                Logger.getLogger(add_employee.class.getName()).log(Level.SEVERE, null, ex);
            }
        
       
        
        
        }
        empid.setText("");
        nic.setText("");
        gender.setSelectedItem("--Select Gender--");
        fname.setText("");
        lname.setText("");
        address.setText("");
        telephone.setText("");
        basicsal.setText("");
        
    }//GEN-LAST:event_deleteActionPerformed

    private void etableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etableMouseClicked
        // TODO add your handling code here:
        
        
             
        int r = etable.getSelectedRow();
        
    String eid = etable.getValueAt(r, 0).toString();
    String enic = etable.getValueAt(r, 1).toString();
    String egender = etable.getValueAt(r, 2).toString();
    String efname = etable.getValueAt(r, 3).toString();
    String elname = etable.getValueAt(r, 4).toString();
    String eaddress= etable.getValueAt(r, 5).toString();
    String etelephone = etable.getValueAt(r, 6).toString();
    String ebasicsal = etable.getValueAt(r, 7).toString();
    
    empid.setText(eid);
    nic.setText(enic);
    gender.setSelectedItem(egender);
    fname.setText(efname);
    lname.setText(elname);
    address.setText(eaddress);
    telephone.setText(etelephone);
    basicsal.setText(ebasicsal);
    
    }//GEN-LAST:event_etableMouseClicked

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void report_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_pnlMouseClicked
        employee_report er1 = new employee_report();
        er1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_report_pnlMouseClicked

    private void telephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneKeyPressed
        // TODO add your handling code here:
        
        //cannot insert charcters  
        
        String tp = telephone.getText();
        
        int length = tp.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            
            if(length<10){
            
                telephone.setEditable(true);
            }
            else{
            
                telephone.setEditable(false);
                
                JOptionPane.showMessageDialog(null,"Invalidate phone number");
            }
        
        }
        
        else{
          if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
              telephone.setEditable(true);
          }
          else{
              telephone.setEditable(false);
          }
        }


    }//GEN-LAST:event_telephoneKeyPressed

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        // TODO add your handling code here:
        
          char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            fname.setEditable(true);
             }
        else{
            fname.setEditable(false);
             JOptionPane.showMessageDialog(null,"can not enter numbers");
        }
    }//GEN-LAST:event_fnameKeyPressed

    private void lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            lname.setEditable(true);
             }
        else{
            lname.setEditable(false);
             JOptionPane.showMessageDialog(null,"can not enter numbers");
        }
         
    }//GEN-LAST:event_lnameKeyPressed

    private void basicsalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basicsalKeyPressed
        // TODO add your handling code here:
        
      //cannot insert charcters   
 char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            basicsal.setEditable(false);
             }
        else{
            basicsal.setEditable(true);
           
        }

        
       
        
    }//GEN-LAST:event_basicsalKeyPressed

    private void nicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyPressed
        if(!(nic.getText().trim().matches("[0-9{9}][V]")));
        {
            
            
        }
       
        
      
    }//GEN-LAST:event_nicKeyPressed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login l1 = new login();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        main m1 = new main();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void headerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseClicked
        attendance s = new attendance();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_headerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new add_employee().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JPanel att_pnl;
    private javax.swing.JPanel background;
    private javax.swing.JTextField basicsal;
    private javax.swing.JButton delete;
    private javax.swing.JPanel ed;
    private javax.swing.JTextField empid;
    private javax.swing.JTable etable;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JPanel header;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField nic;
    private javax.swing.JPanel report_pnl;
    private javax.swing.JButton search;
    private javax.swing.JLabel show_emp_id;
    private javax.swing.JTextField sseid;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
