/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory;

import com.dbconnection.DBconnect;
import com.login.login;
import com.main.main;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author cheythi
 */
public class guns extends javax.swing.JFrame {

    /**
     * Creates new form uniforms
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public guns() {
        initComponents();
        con = DBconnect.connect();
        gun_tbl_load();
        gun_emp_table();
        gauge();
        ak();
        
        header.setBackground(new Color(0,0,0,180));
        logout.setBackground(new Color(255,51,0,180));
        menu.setBackground(new Color(255,51,0,180));
        inventory_menu.setBackground(new Color(255,51,0,180));
        left_pnl.setBackground(new Color(0,0,0,150));
        right_pnl.setBackground(new Color(0,0,0,150));
        
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void gun_tbl_load(){
        try{
            String sql = "SELECT GNO,MODEL FROM gun WHERE NOT EXISTS (SELECT * FROM employee WHERE gun.GNO = employee.GNO)";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery();
            
            gun_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch (Exception e){
            
        }
    }
    
    public void gun_emp_table(){
        try{
            String sql = "SELECT gun.GNO,employee.EID FROM gun,employee WHERE gun.GNO=employee.GNO";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery();
            
            gun_emp_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch (Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        company = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inventory_menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        left_pnl = new javax.swing.JPanel();
        gun_chooser = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gun_tbl = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        control_left_l = new javax.swing.JPanel();
        add_uniform = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        control_left_r = new javax.swing.JPanel();
        delete_uniform = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        uid_box2 = new javax.swing.JPanel();
        gauge_count = new javax.swing.JTextField();
        ak_count = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        right_pnl = new javax.swing.JPanel();
        enter_empid = new javax.swing.JTextField();
        search_empid = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gun_emp_tbl = new javax.swing.JTable();
        control_right_add = new javax.swing.JPanel();
        assign_gun = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        control_right_update = new javax.swing.JPanel();
        assign_gun1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        gun_id = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        update_hidden_eid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(null);

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Log out");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background.add(logout);
        logout.setBounds(0, 800, 780, 50);

        company.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        company.setText("Eagle Security (PVT) LTD ");
        company.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(585, Short.MAX_VALUE)
                .addComponent(company)
                .addGap(545, 545, 545))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(header);
        header.setBounds(0, 0, 1550, 70);

        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Menu");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background.add(menu);
        menu.setBounds(780, 800, 770, 50);

        inventory_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventory_menuMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Inventory");

        javax.swing.GroupLayout inventory_menuLayout = new javax.swing.GroupLayout(inventory_menu);
        inventory_menu.setLayout(inventory_menuLayout);
        inventory_menuLayout.setHorizontalGroup(
            inventory_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
            .addGroup(inventory_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inventory_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        inventory_menuLayout.setVerticalGroup(
            inventory_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(inventory_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inventory_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background.add(inventory_menu);
        inventory_menu.setBounds(0, 70, 1550, 30);

        left_pnl.setBackground(new java.awt.Color(51, 153, 255));

        gun_chooser.setBackground(new java.awt.Color(153, 153, 153));
        gun_chooser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gun_chooser.setForeground(new java.awt.Color(153, 153, 153));
        gun_chooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Gun--", "12 Gauge", "AK 47" }));
        gun_chooser.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Size");

        gun_tbl.setAutoCreateRowSorter(true);
        gun_tbl.setBackground(new java.awt.Color(204, 204, 204));
        gun_tbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gun_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gun_tbl.setGridColor(new java.awt.Color(153, 153, 153));
        gun_tbl.setIntercellSpacing(new java.awt.Dimension(10, 1));
        gun_tbl.setRowHeight(25);
        gun_tbl.setSelectionBackground(new java.awt.Color(204, 204, 204));
        gun_tbl.setSelectionForeground(new java.awt.Color(153, 153, 153));
        gun_tbl.setShowGrid(false);
        gun_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gun_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gun_tbl);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("12 Gauge");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("AK 47");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Now Availables :-");

        control_left_l.setBackground(new java.awt.Color(204, 204, 204));
        control_left_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                control_left_lMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                control_left_lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                control_left_lMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                control_left_lMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                control_left_lMouseReleased(evt);
            }
        });

        add_uniform.setIcon(new javax.swing.ImageIcon("C:\\Users\\cheythi\\Desktop\\Eagle security software\\background\\add.png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("add");

        javax.swing.GroupLayout control_left_lLayout = new javax.swing.GroupLayout(control_left_l);
        control_left_l.setLayout(control_left_lLayout);
        control_left_lLayout.setHorizontalGroup(
            control_left_lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_left_lLayout.createSequentialGroup()
                .addComponent(add_uniform)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        control_left_lLayout.setVerticalGroup(
            control_left_lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_left_lLayout.createSequentialGroup()
                .addComponent(add_uniform)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, control_left_lLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        control_left_r.setBackground(new java.awt.Color(204, 204, 204));
        control_left_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                control_left_rMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                control_left_rMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                control_left_rMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                control_left_rMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                control_left_rMouseReleased(evt);
            }
        });

        delete_uniform.setIcon(new javax.swing.ImageIcon("C:\\Users\\cheythi\\Desktop\\Eagle security software\\background\\delete.png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("delete");

        javax.swing.GroupLayout control_left_rLayout = new javax.swing.GroupLayout(control_left_r);
        control_left_r.setLayout(control_left_rLayout);
        control_left_rLayout.setHorizontalGroup(
            control_left_rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_left_rLayout.createSequentialGroup()
                .addComponent(delete_uniform, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        control_left_rLayout.setVerticalGroup(
            control_left_rLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, control_left_rLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(delete_uniform))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, control_left_rLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        uid_box2.setBackground(new java.awt.Color(51, 0, 204));
        uid_box2.setLayout(null);

        gauge_count.setEditable(false);
        gauge_count.setBackground(new java.awt.Color(102, 102, 102));
        gauge_count.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        gauge_count.setText("10");
        gauge_count.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ak_count.setEditable(false);
        ak_count.setBackground(new java.awt.Color(102, 102, 102));
        ak_count.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ak_count.setText("10");
        ak_count.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\cheythi\\Desktop\\Eagle security software\\background\\gun_icon.png")); // NOI18N

        javax.swing.GroupLayout left_pnlLayout = new javax.swing.GroupLayout(left_pnl);
        left_pnl.setLayout(left_pnlLayout);
        left_pnlLayout.setHorizontalGroup(
            left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_pnlLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(left_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(uid_box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(left_pnlLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(gauge_count, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(ak_count, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(left_pnlLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(left_pnlLayout.createSequentialGroup()
                .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(left_pnlLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(left_pnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(control_left_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(left_pnlLayout.createSequentialGroup()
                                .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(control_left_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(gun_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        left_pnlLayout.setVerticalGroup(
            left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_pnlLayout.createSequentialGroup()
                .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(left_pnlLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gun_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(control_left_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(control_left_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(left_pnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_pnlLayout.createSequentialGroup()
                        .addComponent(uid_box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_pnlLayout.createSequentialGroup()
                        .addGroup(left_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(gauge_count, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(ak_count, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        background.add(left_pnl);
        left_pnl.setBounds(40, 140, 710, 640);

        right_pnl.setBackground(new java.awt.Color(0, 102, 102));

        enter_empid.setBackground(new java.awt.Color(102, 102, 102));
        enter_empid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enter_empid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enter_empid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enter_empidKeyPressed(evt);
            }
        });

        search_empid.setBackground(new java.awt.Color(204, 204, 204));
        search_empid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_empidMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_empidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_empidMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                search_empidMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                search_empidMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Search");

        javax.swing.GroupLayout search_empidLayout = new javax.swing.GroupLayout(search_empid);
        search_empid.setLayout(search_empidLayout);
        search_empidLayout.setHorizontalGroup(
            search_empidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_empidLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        search_empidLayout.setVerticalGroup(
            search_empidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_empidLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        gun_emp_tbl.setAutoCreateRowSorter(true);
        gun_emp_tbl.setBackground(new java.awt.Color(204, 204, 204));
        gun_emp_tbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gun_emp_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gun_emp_tbl.setAutoscrolls(false);
        gun_emp_tbl.setGridColor(new java.awt.Color(153, 153, 153));
        gun_emp_tbl.setIntercellSpacing(new java.awt.Dimension(10, 1));
        gun_emp_tbl.setRowHeight(25);
        gun_emp_tbl.setSelectionBackground(new java.awt.Color(204, 204, 204));
        gun_emp_tbl.setSelectionForeground(new java.awt.Color(153, 153, 153));
        gun_emp_tbl.setShowHorizontalLines(false);
        gun_emp_tbl.setShowVerticalLines(false);
        gun_emp_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gun_emp_tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gun_emp_tbl);

        control_right_add.setBackground(new java.awt.Color(204, 204, 204));
        control_right_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                control_right_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                control_right_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                control_right_addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                control_right_addMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                control_right_addMouseReleased(evt);
            }
        });

        assign_gun.setIcon(new javax.swing.ImageIcon("C:\\Users\\cheythi\\Desktop\\Eagle security software\\background\\add.png")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Give uniform");

        javax.swing.GroupLayout control_right_addLayout = new javax.swing.GroupLayout(control_right_add);
        control_right_add.setLayout(control_right_addLayout);
        control_right_addLayout.setHorizontalGroup(
            control_right_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_right_addLayout.createSequentialGroup()
                .addComponent(assign_gun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        control_right_addLayout.setVerticalGroup(
            control_right_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, control_right_addLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(assign_gun))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, control_right_addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        control_right_update.setBackground(new java.awt.Color(204, 204, 204));
        control_right_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                control_right_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                control_right_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                control_right_updateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                control_right_updateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                control_right_updateMouseReleased(evt);
            }
        });

        assign_gun1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cheythi\\Desktop\\Eagle security software\\background\\update.png")); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Update");

        javax.swing.GroupLayout control_right_updateLayout = new javax.swing.GroupLayout(control_right_update);
        control_right_update.setLayout(control_right_updateLayout);
        control_right_updateLayout.setHorizontalGroup(
            control_right_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_right_updateLayout.createSequentialGroup()
                .addComponent(assign_gun1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        control_right_updateLayout.setVerticalGroup(
            control_right_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, control_right_updateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(assign_gun1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, control_right_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gun_id.setEditable(false);
        gun_id.setBackground(new java.awt.Color(102, 102, 102));
        gun_id.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        gun_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(102, 102, 102));
        fname.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        fname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout right_pnlLayout = new javax.swing.GroupLayout(right_pnl);
        right_pnl.setLayout(right_pnlLayout);
        right_pnlLayout.setHorizontalGroup(
            right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_pnlLayout.createSequentialGroup()
                .addGroup(right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(right_pnlLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(right_pnlLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(gun_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_pnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_pnlLayout.createSequentialGroup()
                                        .addComponent(control_right_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(223, 223, 223))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_pnlLayout.createSequentialGroup()
                                        .addComponent(enter_empid, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(search_empid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(207, 207, 207))))))
                    .addGroup(right_pnlLayout.createSequentialGroup()
                        .addContainerGap(62, Short.MAX_VALUE)
                        .addGroup(right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(right_pnlLayout.createSequentialGroup()
                                    .addComponent(control_right_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(74, 74, 74))
            .addGroup(right_pnlLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        right_pnlLayout.setVerticalGroup(
            right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_pnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_empid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enter_empid, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(43, 43, 43)
                .addGroup(right_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(control_right_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gun_id, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(control_right_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        background.add(right_pnl);
        right_pnl.setBounds(820, 140, 700, 640);

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\cheythi\\Desktop\\Eagle security software\\background\\security.jpg")); // NOI18N
        background.add(image);
        image.setBounds(0, 0, 1550, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(update_hidden_eid)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(update_hidden_eid)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventory_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventory_menuMouseClicked
        inventory_menu im1 = new inventory_menu();    
        im1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventory_menuMouseClicked

    private void enter_empidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter_empidKeyPressed
      
        String eid = enter_empid.getText();
          
          
        int length = eid.length();
          
          
        char c = evt.getKeyChar();
          
          
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
              
            if(length<4){
                 
                enter_empid.setEditable(true);
            }
            else{
                  enter_empid.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                enter_empid.setEditable(true);
            }
            else{
                  enter_empid.setEditable(false);
          }
        }
        
    }//GEN-LAST:event_enter_empidKeyPressed

    private void control_left_lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_lMouseClicked

        if(!(gun_chooser.getSelectedItem().toString().equals("--Select Gun--"))){
            String model = gun_chooser.getSelectedItem().toString();

                try{
                    String q = "INSERT INTO gun(MODEL) values ('"+ model +"')";
                    pst = (PreparedStatement) con.prepareStatement(q);
                    pst.execute();

                }catch (Exception e) {  
                }
                gun_tbl_load();
                gun_chooser.setSelectedItem("--Select Gun--");
                gauge();
                ak();
        }
        else{
            JOptionPane.showMessageDialog(this, "Select Model before add gun");
        }
    }//GEN-LAST:event_control_left_lMouseClicked

    private void control_left_lMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_lMousePressed
        control_left_l.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_control_left_lMousePressed

    private void control_left_lMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_lMouseReleased
        control_left_l.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_left_lMouseReleased

    private void control_left_lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_lMouseEntered
       control_left_l.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_left_lMouseEntered

    private void control_left_lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_lMouseExited
        control_left_l.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_control_left_lMouseExited

    private void control_left_rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_rMouseClicked

        if(!(gun_id.getText().equals(""))){
            int d = JOptionPane.showConfirmDialog(this,"Do you really want to delete?","Delete gun",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(d == 0){
                String id = gun_id.getText();

                String del = "DELETE from gun WHERE GNO = '"+ id +"'";
                try {
                    pst = (PreparedStatement) con.prepareStatement(del);
                    pst.execute();
                    
                    String model = gun_chooser.getSelectedItem().toString();
                    try{
                        String dg = "INSERT INTO disposal_gun (MODEL) values ('"+ model +"')";
                        pst = (PreparedStatement) con.prepareStatement(dg);
                        pst.execute();
                    }
                    catch(Exception e){
                        JOptionPane.showConfirmDialog(null,e);
                    }

                    gun_tbl_load();
                    gauge();
                    ak();
                    gun_id.setText("");
                    gun_chooser.setSelectedItem("--Select Gun--");
                    
                } catch (Exception e) {

                }
            }
            else{
                gun_id.setText("");
                gun_chooser.setSelectedItem("--Select Gun--");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a gun you want to delete!");
        }
    }//GEN-LAST:event_control_left_rMouseClicked

    private void control_left_rMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_rMouseEntered
        control_left_r.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_left_rMouseEntered

    private void control_left_rMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_rMouseExited
        control_left_r.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_control_left_rMouseExited

    private void control_left_rMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_rMousePressed
        control_left_r.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_control_left_rMousePressed

    private void control_left_rMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_left_rMouseReleased
        control_left_r.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_left_rMouseReleased

    private void gun_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gun_tblMouseClicked
        int r = gun_tbl.getSelectedRow();
        
        String gno = gun_tbl.getValueAt(r, 0).toString();
        String model = gun_tbl.getValueAt(r, 1).toString();
        
        gun_id.setText(gno);
        gun_chooser.setSelectedItem(model);
    }//GEN-LAST:event_gun_tblMouseClicked

    private void control_right_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_addMouseClicked

        if(gun_id.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Select gun");
        }
        else if(enter_empid.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Enter employee ID and search");
        }
        else if(fname.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Search employee ID");
        }
        else{
            String gno = gun_id.getText().toString();
            String empid = enter_empid.getText().toString();
            
            try{
                String q = "UPDATE employee SET GNO = '"+ gno +"' WHERE EID = '"+ empid +"'";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.execute();
                
                String model = gun_chooser.getSelectedItem().toString();
                String reid = enter_empid.getText().toString();
                try{
                    String ru = "INSERT INTO gun_employee_report(MODEL,EID) values ('"+ model +"','"+ reid +"')";
                    pst = (PreparedStatement) con.prepareStatement(ru);
                    pst.execute();
                }
                catch(Exception e){
                    JOptionPane.showConfirmDialog(null,e);
                }
            }catch (Exception e) {
                JOptionPane.showConfirmDialog(null,e);
            }
            gun_tbl_load();
            gun_emp_table();
            gauge();
            ak();
            enter_empid.setText("");
            gun_chooser.setSelectedItem("--Select Gun--");
            gun_id.setText("");
            fname.setText("");
        }
    }//GEN-LAST:event_control_right_addMouseClicked

    private void control_right_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_addMouseEntered
        control_right_add.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_right_addMouseEntered

    private void control_right_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_addMouseExited
        control_right_add.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_control_right_addMouseExited

    private void control_right_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_addMousePressed
        control_right_add.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_control_right_addMousePressed

    private void control_right_addMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_addMouseReleased
        control_right_add.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_right_addMouseReleased

    private void control_right_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_updateMouseClicked
       if(gun_id.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Select gun");
        }
        else if(fname.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Select Employer");
        }
        else{
            String gno = gun_id.getText().toString();
            String empid = update_hidden_eid.getText().toString();
            
            try{
                String q = "UPDATE employee SET GNO = '"+ gno +"' WHERE EID = '"+ empid +"'";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.execute();
                
                String gmodel = gun_chooser.getSelectedItem().toString();
                String greid = update_hidden_eid.getText().toString();
                try{
                    String uru = "INSERT INTO gun_employee_report(MODEL,EID) values ('"+ gmodel +"','"+ greid +"')";
                    pst = (PreparedStatement) con.prepareStatement(uru);
                    pst.execute();
                }
                catch(Exception e){
                    JOptionPane.showConfirmDialog(null,e);
                }
                }catch (Exception e) {
                    JOptionPane.showConfirmDialog(null,e);
                }
                gun_tbl_load();
                gun_emp_table();
                gauge();
                ak();
                enter_empid.setText("");
                gun_chooser.setSelectedItem("--Select Gun--");
                gun_id.setText("");
                fname.setText("");
                update_hidden_eid.setText("");
        }
    }//GEN-LAST:event_control_right_updateMouseClicked

    private void control_right_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_updateMouseEntered
        control_right_update.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_right_updateMouseEntered

    private void control_right_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_updateMouseExited
        control_right_update.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_control_right_updateMouseExited

    private void control_right_updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_updateMousePressed
        control_right_update.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_control_right_updateMousePressed

    private void control_right_updateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_control_right_updateMouseReleased
        control_right_update.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_control_right_updateMouseReleased

    private void search_empidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_empidMouseClicked
        if(!(enter_empid.getText().equals(""))){
            String eid = enter_empid.getText();

            try{

                String q = "SELECT FIRSTNAME FROM employee WHERE EID = '" + eid + "'";
                pst = (PreparedStatement) con.prepareStatement(q);
                rs = (ResultSet) pst.executeQuery();

                if(rs.next()){
                    String name = rs.getString("FIRSTNAME");
                    fname.setText(name);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Invalid employee ID");
                    enter_empid.setText("");
                }

            }catch (Exception e) {    
                JOptionPane.showConfirmDialog(null,e);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter Employee ID");
        }
    }//GEN-LAST:event_search_empidMouseClicked

    private void search_empidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_empidMouseEntered
        search_empid.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_search_empidMouseEntered

    private void search_empidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_empidMouseExited
        search_empid.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_search_empidMouseExited

    private void search_empidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_empidMousePressed
        search_empid.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_search_empidMousePressed

    private void search_empidMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_empidMouseReleased
        search_empid.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_search_empidMouseReleased

    private void gun_emp_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gun_emp_tblMouseClicked
        int e = gun_emp_tbl.getSelectedRow();
        
        String uno = gun_emp_tbl.getValueAt(e, 0).toString();
        String eid = gun_emp_tbl.getValueAt(e, 1).toString();
        
        update_hidden_eid.setText(eid);
          try{
            String q = "SELECT FIRSTNAME FROM employee WHERE EID = '" + eid + "'";
            pst = (PreparedStatement) con.prepareStatement(q);
            rs = (ResultSet) pst.executeQuery();
           
            if(rs.next()){
                String name = rs.getString("FIRSTNAME");
                fname.setText(name);
            }
          }catch (Exception p) {
              int showConfirmDialog = JOptionPane.showConfirmDialog(null,p);
          }
    }//GEN-LAST:event_gun_emp_tblMouseClicked

    private void companyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyMouseClicked
        gun_chooser.setSelectedItem("--Select Gun--");
        enter_empid.setText("");
        gun_id.setText("");
        fname.setText("");
        update_hidden_eid.setText("");
    }//GEN-LAST:event_companyMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        main m1 = new main();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login l1 = new login();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void gauge(){
        try{
            String q = "SELECT COUNT(MODEL) AS C FROM gun WHERE MODEL='12 Gauge' AND NOT EXISTS (SELECT * FROM employee WHERE gun.GNO = employee.GNO)";
            pst = (PreparedStatement) con.prepareStatement(q);
            rs = (ResultSet) pst.executeQuery();

            if(rs.next()){
                String c = rs.getString(1);
                gauge_count.setText(c);
            }

        }catch (Exception e) {    
            int showConfirmDialog = JOptionPane.showConfirmDialog(null,e);
        }
    }
    
    private void ak(){
        try{
            String q = "SELECT COUNT(MODEL) AS C FROM gun WHERE MODEL='AK 47' AND NOT EXISTS (SELECT * FROM employee WHERE gun.GNO = employee.GNO)";
            pst = (PreparedStatement) con.prepareStatement(q);
            rs = (ResultSet) pst.executeQuery();

            if(rs.next()){
                String c = rs.getString(1);
                ak_count.setText(c);
            }

        }catch (Exception e) {    
            int showConfirmDialog = JOptionPane.showConfirmDialog(null,e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_uniform;
    private javax.swing.JTextField ak_count;
    private javax.swing.JLabel assign_gun;
    private javax.swing.JLabel assign_gun1;
    private javax.swing.JPanel background;
    private javax.swing.JLabel company;
    private javax.swing.JPanel control_left_l;
    private javax.swing.JPanel control_left_r;
    private javax.swing.JPanel control_right_add;
    private javax.swing.JPanel control_right_update;
    private javax.swing.JLabel delete_uniform;
    private javax.swing.JTextField enter_empid;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gauge_count;
    private javax.swing.JComboBox<String> gun_chooser;
    private javax.swing.JTable gun_emp_tbl;
    private javax.swing.JTextField gun_id;
    private javax.swing.JTable gun_tbl;
    private javax.swing.JPanel header;
    private javax.swing.JLabel image;
    private javax.swing.JPanel inventory_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel left_pnl;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel right_pnl;
    private javax.swing.JPanel search_empid;
    private javax.swing.JPanel uid_box2;
    private javax.swing.JLabel update_hidden_eid;
    // End of variables declaration//GEN-END:variables
}
